name: Lint and test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install .[dev]

      - name: Lint 🔍
        run: flake8 jsonrpyc tests

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install .[dev]

      - name: Typecheck 🥊
        run: mypy jsonrpyc

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install -U twine build

      - name: Check bundling 📦
        run: python -m build

      - name: Check setup 🚦
        run: twine check "dist/jsonrpyc-*.tar.gz"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    name: test (python ${{ matrix.python-version }})
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install .[dev]

      - name: Test 🎢
        run: pytest tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools wheel
          pip install .[dev]

      - name: Run coverage test 🎢
        run: pytest --cov=jsonrpyc --cov-report xml:coverage.xml

      - name: Upload report 🔝
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
